spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hr
    username:
    password:
    driverClassName: org.postgresql.Driver

server:
  port: 8085
  servlet:
    context-path: /api/v1/

liquibase:
  enabled: true
  drop-first: false
  change-log: classpath:db/changelog/db.changelog-master.yaml
  default-schema: public
